### ISSUE TITLE
On click of the image, the text area and shapes are not coming beside but somewhere else

### ISSUE THREAD

**Issue by suresh2291** [dallin-christensen/react-img-markdown#2] opened 2023-03-24 09:56 UTC
![Facebook - Google Chrome 24-Mar-23 3_23_31 PM](https://user-images.githubusercontent.com/9513995/227488500-9c7ee9c8-83f9-4629-9456-f5ed8f23d71c.png)
Hi Dallin.
You have made a very great tool for image annotations, I appreciate your work.
But I am facing some issues, when I select any text or draw something , the text are is not coming beside but some where else.

This is the configuration I am using?
 <ImgMarkup
            className="modal-image"
                imgSrc={images[selectedImageIndex]}
                imgStyles={{ height: 800, width: 800 }}
                key={selectedImageIndex}
                onSave={(uri) => console.log({ uri })}
              >
                {({
                  activeColor,
                  activeStrokeWidth,
                  activeType,
                  activeFontSize,
                  setActiveColor,
                  setActiveStrokeWidth,
                  setActiveType,
                  setActiveFontSize,
                  undo,
                  save,
                  deletePath,
                  activePathId,
                  imgMarkupModifiers,
                }) => (
                  <div ref={imgMarkupModifiers}>
                    <label htmlFor="type">Type:</label>
                    <select
                      name="type"
                      value={activeType}
                      onChange={(e) => setActiveType(e.target.value)}
                    >
                      <option value="line">line</option>
                      <option value="arrow">arrow</option>
                      <option value="rect">rect</option>
                      <option value="ellipse">ellipse</option>
                      <option value="text">text</option>
                    </select>

                    <label htmlFor="color">Color:</label>
                    <select
                      name="color"
                      value={activeColor}
                      onChange={(e) => setActiveColor(e.target.value)}
                    >
                      <option value="red">red</option>
                      <option value="green">green</option>
                      <option value="#0af">blue</option>
                      <option value="orange">orange</option>
                    </select>

                    <label htmlFor="stroke-width">width</label>
                    <input
                      name="stroke-width"
                      type="number"
                      value={activeStrokeWidth}
                      onChange={(e) => setActiveStrokeWidth(e.target.value)}
                    />

                    <label htmlFor="font-size">font size</label>
                    <input
                      name="font-size"
                      type="number"
                      value={activeFontSize}
                      onChange={(e) => setActiveFontSize(e.target.value)}
                    />
                    <button onClick={save}>save</button>
                    <button onClick={undo}>undo</button>
                    {activePathId ? (
                      <button onClick={() => deletePath(activePathId)}>
                        delete
                      </button>
                    ) : null}
                  </div>
                )}
              </ImgMarkup>
Please help me out

**Comment by dallin-christensen** [comment] 2023-08-23 17:32
Hello, @suresh2291 , my apologies for taking some time to get back to you. I took a moment to run your code locally and was not able to reproduce this issue. My best guess would be that there are some cascading styles in your environment that are affecting the positioning of the elements within the ImgMarkup component. I see that you are using a modal UI combined with ImgMarkup, perhaps the modal's absolute styles are affecting the textarea and other elements somehow? I would dig into your browser's devtools to expose the styles that are being imposed on the elements within ImgMarkup, and see if that yields any results. 

For now, I'm going to close this ticket but I'm happy to re-open if we find a bug within this project. Thanks and let me know if I can be of any more help.

**Closed as completed** 2023-08-23 17:33 UTC
